apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api-deployment
  template:
    metadata:
      labels:
        app: customer-api-deployment
    spec:
      containers:
        - name: customer-api-deployment
          image: customer-app:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_URLS
              value: http://+:3001
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          ports:
            - containerPort: 3001
