apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api-deployment
  template:
    metadata:
      labels:
        app: order-api-deployment
    spec:
      containers:
        - name: order-api-deployment
          image: order-app:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_URLS
              value: http://+:3002
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          ports:
            - containerPort: 3002
