apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  selector:
    app: order-api-deployment
  ports:
    - port: 8080
      targetPort: 3002
  type: {{ .Values.order.service.type }}
