apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-mssql
  template:
    metadata:
      labels:
        app: customer-mssql
    spec:
      containers:
        - name: customer-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Qwe12345"
          ports:
            - containerPort: 1433
