apiVersion: v1
kind: Service
metadata:
  name: customer-mssql
spec:
  selector:
    app: customer-mssql
  ports:
    - port: 81
      targetPort: 1433
  type: {{ .Values.customermssql.service.type }}
