apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  namespace: customerapp
  labels: { "type": "server", "env": "multi" }
spec:
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq-cont
          image: rabbitmq:3-management
          imagePullPolicy: Always
          ports:
            - containerPort: 15672
