apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: port-1
      port: 15672
      targetPort: 15672
    - name: port-2
      port: 5672
      targetPort: 5672
  type: {{ .Values.rabbit.service.type }}
