apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
spec:
  selector:
    matchLabels:
      component: customerapi
  replicas: 1
  template:
    metadata:
      labels:
        component: customerapi
    spec:
      containers:
        - name: customerapi
          image: customer-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: ASPNETCORE_URLS
              value: http://+:3001
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"